/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snmp;

import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import java.util.scaner;
import org.snmp4j.CommunityTarget;
import org.snmp4j.PDU;
import org.snmp4j.Snmp;
import org.snmp4j.Target;
import org.snmp4j.TransportMapping;
import org.snmp4j.event.ResponseEvent;
import org.snmp4j.mp.SnmpConstants;
import org.snmp4j.smi.Address;
import org.snmp4j.smi.GenericAddress;
import org.snmp4j.smi.OID;
import org.snmp4j.smi.OctetString;
import org.snmp4j.smi.VariableBinding;
import org.snmp4j.transport.DefaultUdpTransportMapping;

/**
 *
 * @author user
 */
public class SNMP_UI extends javax.swing.JFrame {
    
   String ip;
   String alamat;
   String kom;  
   String hasil;
   String oid;
   String oidname;
   int i = 0;
    
    public SNMP_UI() {
        initComponents();
        
    }
    
    public void opensnmp () {
     
        alamat = "udp:"+ip+"/161";
        
    /**
    * Port 161 is used for Read and Other operations
    * Port 162 is used for the trap generation
    */
        try{
        
        SnmpWalk client = new SnmpWalk(alamat,kom);
        client.start();
        /**
        * OID - .1.3.6.1.2.1.1.1.0 => SysDec
        * OID - .1.3.6.1.2.1.1.5.0 => SysName
        * => MIB explorer will be usefull here, as discussed in previous article
        */
        String sysDescr = client.getAsString(new OID(oid));
        hasil = sysDescr;
        output.setText(oidname+": "+hasil);
        }catch(Exception e){
             System.out.println("Error : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtOid = new javax.swing.JTextField();
        oi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        txtComm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btSysD = new javax.swing.JButton();
        btSysUt = new javax.swing.JButton();
        btSysN = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHsl = new javax.swing.JTable();
        btHS = new javax.swing.JButton();
        btHSt = new javax.swing.JButton();
        btHD = new javax.swing.JButton();
        btIR = new javax.swing.JButton();
        btIHE = new javax.swing.JButton();
        btIAE = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btSIP = new javax.swing.JButton();
        btSOP = new javax.swing.JButton();
        btSIV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 522));
        setPreferredSize(new java.awt.Dimension(450, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 810, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Aplikasi SNMP Java");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(null);

        txtOid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtOid);
        txtOid.setBounds(110, 110, 150, 30);

        oi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oi.setForeground(new java.awt.Color(255, 255, 255));
        oi.setText("OID");
        jPanel1.add(oi);
        oi.setBounds(70, 120, 24, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IP Address");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 64, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Community");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 72, 17);

        txtIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpActionPerformed(evt);
            }
        });
        jPanel1.add(txtIp);
        txtIp.setBounds(110, 30, 151, 30);
        jPanel1.add(output);
        output.setBounds(50, 200, 240, 36);

        go.setText("RUN");
        go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goMouseClicked(evt);
            }
        });
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go);
        go.setBounds(50, 160, 60, 30);

        txtComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommActionPerformed(evt);
            }
        });
        jPanel1.add(txtComm);
        txtComm.setBounds(110, 70, 151, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("List Oid");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(505, 20, 50, 14);

        btSysD.setText("sysDecsr");
        btSysD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSysDActionPerformed(evt);
            }
        });
        jPanel1.add(btSysD);
        btSysD.setBounds(330, 80, 100, 23);

        btSysUt.setText("sysUpTime");
        btSysUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSysUtActionPerformed(evt);
            }
        });
        jPanel1.add(btSysUt);
        btSysUt.setBounds(330, 110, 100, 23);

        btSysN.setText("sysName");
        btSysN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSysNActionPerformed(evt);
            }
        });
        jPanel1.add(btSysN);
        btSysN.setBounds(330, 140, 100, 23);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(300, 2, 0, 460);

        tblHsl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP Address", "Community", "OID", "Value"
            }
        ));
        jScrollPane1.setViewportView(tblHsl);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 740, 160);

        btHS.setText("hrSystem");
        btHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHSActionPerformed(evt);
            }
        });
        jPanel1.add(btHS);
        btHS.setBounds(440, 80, 80, 23);

        btHSt.setText("hrStorage");
        btHSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHStActionPerformed(evt);
            }
        });
        jPanel1.add(btHSt);
        btHSt.setBounds(440, 110, 81, 23);

        btHD.setText("hrDevice");
        btHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHDActionPerformed(evt);
            }
        });
        jPanel1.add(btHD);
        btHD.setBounds(440, 140, 80, 23);

        btIR.setText("ipInReceives");
        btIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIRActionPerformed(evt);
            }
        });
        jPanel1.add(btIR);
        btIR.setBounds(530, 80, 100, 23);

        btIHE.setText("ipInHdrErrors");
        btIHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIHEActionPerformed(evt);
            }
        });
        jPanel1.add(btIHE);
        btIHE.setBounds(530, 110, 100, 23);

        btIAE.setText("ipInAddErrors");
        btIAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIAEActionPerformed(evt);
            }
        });
        jPanel1.add(btIAE);
        btIAE.setBounds(530, 140, 100, 23);

        btReset.setText("RESET");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        jPanel1.add(btReset);
        btReset.setBounds(130, 160, 73, 30);

        btSIP.setText("snmpInPkts");
        btSIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSIPActionPerformed(evt);
            }
        });
        jPanel1.add(btSIP);
        btSIP.setBounds(640, 80, 130, 23);

        btSOP.setText("snmpOutPkts");
        btSOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSOPActionPerformed(evt);
            }
        });
        jPanel1.add(btSOP);
        btSOP.setBounds(640, 110, 130, 23);

        btSIV.setText("snmpInBadVersions");
        btSIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSIVActionPerformed(evt);
            }
        });
        jPanel1.add(btSIV);
        btSIV.setBounds(640, 140, 130, 23);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("System");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(364, 60, 40, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Host");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 60, 50, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(570, 60, 30, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SNMP");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(690, 60, 50, 14);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(220, 160, 55, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpActionPerformed

    private void goMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goMouseClicked
        // TODO add your handling code here:
        this.ip = txtIp.getText();
        this.kom = txtComm.getText();
        this.oid = txtOid.getText();
        if(ip.equals("") && kom.equals("")){
            JOptionPane.showMessageDialog(null, "IP Address dan Community harus diisi!");
        }else{
            if(oid.equals("")){
                JOptionPane.showMessageDialog(null, "OID harus diisi!");
            }
            opensnmp();
        }
        
        
    }//GEN-LAST:event_goMouseClicked

    private void btSysDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSysDActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.1.1.0";
        this.oidname = "sysDescr";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btSysDActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        this.ip = txtIp.getText();
        this.kom = txtComm.getText();
        this.oid = txtOid.getText();
        this.hasil = output.getText();
        
        if(i==0){
            i++;
        }
        else{
            Object[] row = { ip, kom, oid, hasil };
            DefaultTableModel model = (DefaultTableModel) tblHsl.getModel();
            model.addRow(row);
        }
    }//GEN-LAST:event_goActionPerformed

    private void btSysUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSysUtActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.1.3.0";
        this.oidname = "sysUpTime";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btSysUtActionPerformed

    private void btSysNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSysNActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.1.5.0";
        this.oidname = "sysName";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btSysNActionPerformed

    private void txtCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommActionPerformed

    private void btHStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHStActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.25.2.2.0";
        this.oidname = "hrMemorySize";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btHStActionPerformed

    private void btHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHSActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.25.1.1.0";
        this.oidname = "hrSystemUptime";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btHSActionPerformed

    private void btHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHDActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.25.3.2.1.1.0";
        this.oidname = "hrDeviceIndex";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btHDActionPerformed

    private void btIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIRActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.4.3.0";
        this.oidname = "ipInReceives";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btIRActionPerformed

    private void btIHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIHEActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.4.4.0";
        this.oidname = "ipInHdrErrors";
        txtOid.setText(oid);
        
    }//GEN-LAST:event_btIHEActionPerformed

    private void btIAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIAEActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.4.5.0";
        this.oidname = "ipInAddErrors";
        txtOid.setText(oid);
    }//GEN-LAST:event_btIAEActionPerformed

    private void btSIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSIPActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.11.1.0";
        this.oidname = "snmpInPkts";
        txtOid.setText(oid);
    }//GEN-LAST:event_btSIPActionPerformed

    private void btSOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSOPActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.11.2.0";
        this.oidname = "snmpOutPkts";
        txtOid.setText(oid);
    }//GEN-LAST:event_btSOPActionPerformed

    private void btSIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSIVActionPerformed
        // TODO add your handling code here:
        this.oid = "1.3.6.1.2.1.11.3.0";
        this.oidname = "snmpInBadVersions";
        txtOid.setText(oid);
    }//GEN-LAST:event_btSIVActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        txtIp.setText("");
        txtComm.setText("");
        txtOid.setText("");
        DefaultTableModel dm = (DefaultTableModel)tblHsl.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
    }//GEN-LAST:event_btResetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SNMP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SNMP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SNMP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SNMP_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SNMP_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHD;
    private javax.swing.JButton btHS;
    private javax.swing.JButton btHSt;
    private javax.swing.JButton btIAE;
    private javax.swing.JButton btIHE;
    private javax.swing.JButton btIR;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSIP;
    private javax.swing.JButton btSIV;
    private javax.swing.JButton btSOP;
    private javax.swing.JButton btSysD;
    private javax.swing.JButton btSysN;
    private javax.swing.JButton btSysUt;
    private javax.swing.JButton exit;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel oi;
    private javax.swing.JTextField output;
    private javax.swing.JTable tblHsl;
    private javax.swing.JTextField txtComm;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtOid;
    // End of variables declaration//GEN-END:variables

    

}
